export const HOURS_SELECT = [
  { key: "000", value: "12:00 AM", selected: false },
  { key: "100", value: "1:00 AM", selected: false },
  { key: "200", value: "2:00 AM", selected: false },
  { key: "300", value: "3:00 AM", selected: false },
  { key: "400", value: "4:00 AM", selected: false },
  { key: "500", value: "5:00 AM", selected: false },
  { key: "600", value: "6:00 AM", selected: false },
  { key: "700", value: "7:00 AM", selected: false },
  { key: "800", value: "8:00 AM", selected: false },
  { key: "900", value: "9:00 AM", selected: false },
  { key: "1000", value: "10:00 AM", selected: false },
  { key: "1100", value: "11:00 AM", selected: false },
  { key: "1200", value: "12:00 PM", selected: false },
  { key: "1300", value: "1:00 PM", selected: false },
  { key: "1400", value: "2:00 PM", selected: false },
  { key: "1500", value: "3:00 PM", selected: false },
  { key: "1600", value: "4:00 PM", selected: false },
  { key: "1700", value: "5:00 PM", selected: false },
  { key: "1800", value: "6:00 PM", selected: false },
  { key: "1900", value: "7:00 PM", selected: false },
  { key: "2000", value: "8:00 PM", selected: false },
  { key: "2100", value: "9:00 PM", selected: false },
  { key: "2200", value: "10:00 PM", selected: false },
  { key: "2300", value: "11:00 PM", selected: false },
] as const;

export const THIRTY_SELECT = [
  { key: "000", value: "12:00 AM", selected: false },
  { key: "030", value: "12:30 AM", selected: false },
  { key: "100", value: "1:00 AM", selected: false },
  { key: "130", value: "1:30 AM", selected: false },
  { key: "200", value: "2:00 AM", selected: false },
  { key: "230", value: "2:30 AM", selected: false },
  { key: "300", value: "3:00 AM", selected: false },
  { key: "330", value: "3:30 AM", selected: false },
  { key: "400", value: "4:00 AM", selected: false },
  { key: "430", value: "4:30 AM", selected: false },
  { key: "500", value: "5:00 AM", selected: false },
  { key: "530", value: "5:30 AM", selected: false },
  { key: "600", value: "6:00 AM", selected: false },
  { key: "630", value: "6:30 AM", selected: false },
  { key: "700", value: "7:00 AM", selected: false },
  { key: "730", value: "7:30 AM", selected: false },
  { key: "800", value: "8:00 AM", selected: false },
  { key: "830", value: "8:30 AM", selected: false },
  { key: "900", value: "9:00 AM", selected: false },
  { key: "930", value: "9:30 AM", selected: false },
  { key: "1000", value: "10:00 AM", selected: false },
  { key: "1030", value: "10:30 AM", selected: false },
  { key: "1100", value: "11:00 AM", selected: false },
  { key: "1130", value: "11:30 AM", selected: false },
  { key: "1200", value: "12:00 PM", selected: false },
  { key: "1230", value: "12:30 PM", selected: false },
  { key: "1300", value: "1:00 PM", selected: false },
  { key: "1330", value: "1:30 PM", selected: false },
  { key: "1400", value: "2:00 PM", selected: false },
  { key: "1430", value: "2:30 PM", selected: false },
  { key: "1500", value: "3:00 PM", selected: false },
  { key: "1530", value: "3:30 PM", selected: false },
  { key: "1600", value: "4:00 PM", selected: false },
  { key: "1630", value: "4:30 PM", selected: false },
  { key: "1700", value: "5:00 PM", selected: false },
  { key: "1730", value: "5:30 PM", selected: false },
  { key: "1800", value: "6:00 PM", selected: false },
  { key: "1830", value: "6:30 PM", selected: false },
  { key: "1900", value: "7:00 PM", selected: false },
  { key: "1930", value: "7:30 PM", selected: false },
  { key: "2000", value: "8:00 PM", selected: false },
  { key: "2030", value: "8:30 PM", selected: false },
  { key: "2100", value: "9:00 PM", selected: false },
  { key: "2130", value: "9:30 PM", selected: false },
  { key: "2200", value: "10:00 PM", selected: false },
  { key: "2230", value: "10:30 PM", selected: false },
  { key: "2300", value: "11:00 PM", selected: false },
  { key: "2330", value: "11:30 PM", selected: false },
] as const;

export const FIFTEEN_SELECT = [
  { key: "000", value: "12:00 AM", selected: false },
  { key: "015", value: "12:15 AM", selected: false },
  { key: "030", value: "12:30 AM", selected: false },
  { key: "045", value: "12:45 AM", selected: false },
  { key: "100", value: "1:00 AM", selected: false },
  { key: "115", value: "1:15 AM", selected: false },
  { key: "130", value: "1:30 AM", selected: false },
  { key: "145", value: "1:45 AM", selected: false },
  { key: "200", value: "2:00 AM", selected: false },
  { key: "215", value: "2:15 AM", selected: false },
  { key: "230", value: "2:30 AM", selected: false },
  { key: "245", value: "2:45 AM", selected: false },
  { key: "300", value: "3:00 AM", selected: false },
  { key: "315", value: "3:15 AM", selected: false },
  { key: "330", value: "3:30 AM", selected: false },
  { key: "345", value: "3:45 AM", selected: false },
  { key: "400", value: "4:00 AM", selected: false },
  { key: "415", value: "4:15 AM", selected: false },
  { key: "430", value: "4:30 AM", selected: false },
  { key: "445", value: "4:45 AM", selected: false },
  { key: "500", value: "5:00 AM", selected: false },
  { key: "515", value: "5:15 AM", selected: false },
  { key: "530", value: "5:30 AM", selected: false },
  { key: "545", value: "5:45 AM", selected: false },
  { key: "600", value: "6:00 AM", selected: false },
  { key: "615", value: "6:15 AM", selected: false },
  { key: "630", value: "6:30 AM", selected: false },
  { key: "645", value: "6:45 AM", selected: false },
  { key: "700", value: "7:00 AM", selected: false },
  { key: "715", value: "7:15 AM", selected: false },
  { key: "730", value: "7:30 AM", selected: false },
  { key: "745", value: "7:45 AM", selected: false },
  { key: "800", value: "8:00 AM", selected: false },
  { key: "815", value: "8:15 AM", selected: false },
  { key: "830", value: "8:30 AM", selected: false },
  { key: "845", value: "8:45 AM", selected: false },
  { key: "900", value: "9:00 AM", selected: false },
  { key: "915", value: "9:15 AM", selected: false },
  { key: "930", value: "9:30 AM", selected: false },
  { key: "945", value: "9:45 AM", selected: false },
  { key: "1000", value: "10:00 AM", selected: false },
  { key: "1015", value: "10:15 AM", selected: false },
  { key: "1030", value: "10:30 AM", selected: false },
  { key: "1045", value: "10:45 AM", selected: false },
  { key: "1100", value: "11:00 AM", selected: false },
  { key: "1115", value: "11:15 AM", selected: false },
  { key: "1130", value: "11:30 AM", selected: false },
  { key: "1145", value: "11:45 AM", selected: false },
  { key: "1200", value: "12:00 PM", selected: false },
  { key: "1215", value: "12:15 PM", selected: false },
  { key: "1230", value: "12:30 PM", selected: false },
  { key: "1245", value: "12:45 PM", selected: false },
  { key: "1300", value: "1:00 PM", selected: false },
  { key: "1315", value: "1:15 PM", selected: false },
  { key: "1330", value: "1:30 PM", selected: false },
  { key: "1345", value: "1:45 PM", selected: false },
  { key: "1400", value: "2:00 PM", selected: false },
  { key: "1415", value: "2:15 PM", selected: false },
  { key: "1430", value: "2:30 PM", selected: false },
  { key: "1445", value: "2:45 PM", selected: false },
  { key: "1500", value: "3:00 PM", selected: false },
  { key: "1515", value: "3:15 PM", selected: false },
  { key: "1530", value: "3:30 PM", selected: false },
  { key: "1545", value: "3:45 PM", selected: false },
  { key: "1600", value: "4:00 PM", selected: false },
  { key: "1615", value: "4:15 PM", selected: false },
  { key: "1630", value: "4:30 PM", selected: false },
  { key: "1645", value: "4:45 PM", selected: false },
  { key: "1700", value: "5:00 PM", selected: false },
  { key: "1715", value: "5:15 PM", selected: false },
  { key: "1730", value: "5:30 PM", selected: false },
  { key: "1745", value: "5:45 PM", selected: false },
  { key: "1800", value: "6:00 PM", selected: false },
  { key: "1815", value: "6:15 PM", selected: false },
  { key: "1830", value: "6:30 PM", selected: false },
  { key: "1845", value: "6:45 PM", selected: false },
  { key: "1900", value: "7:00 PM", selected: false },
  { key: "1915", value: "7:15 PM", selected: false },
  { key: "1930", value: "7:30 PM", selected: false },
  { key: "1945", value: "7:45 PM", selected: false },
  { key: "2000", value: "8:00 PM", selected: false },
  { key: "2015", value: "8:15 PM", selected: false },
  { key: "2030", value: "8:30 PM", selected: false },
  { key: "2045", value: "8:45 PM", selected: false },
  { key: "2100", value: "9:00 PM", selected: false },
  { key: "2115", value: "9:15 PM", selected: false },
  { key: "2130", value: "9:30 PM", selected: false },
  { key: "2145", value: "9:45 PM", selected: false },
  { key: "2200", value: "10:00 PM", selected: false },
  { key: "2215", value: "10:15 PM", selected: false },
  { key: "2230", value: "10:30 PM", selected: false },
  { key: "2245", value: "10:45 PM", selected: false },
  { key: "2300", value: "11:00 PM", selected: false },
  { key: "2315", value: "11:15 PM", selected: false },
  { key: "2330", value: "11:30 PM", selected: false },
  { key: "2345", value: "11:45 PM", selected: false },
] as const;

export const IANNA_TIME_ZONES = [
  { key: "Africa/Abidjan", value: "Africa/Abidjan", selected: false },
  { key: "Africa/Accra", value: "Africa/Accra", selected: false },
  { key: "Africa/Algiers", value: "Africa/Algiers", selected: false },
  { key: "Africa/Bissau", value: "Africa/Bissau", selected: false },
  { key: "Africa/Cairo", value: "Africa/Cairo", selected: false },
  { key: "Africa/Casablanca", value: "Africa/Casablanca", selected: false },
  { key: "Africa/Ceuta", value: "Africa/Ceuta", selected: false },
  { key: "Africa/El_Aaiun", value: "Africa/El_Aaiun", selected: false },
  { key: "Africa/Johannesburg", value: "Africa/Johannesburg", selected: false },
  { key: "Africa/Juba", value: "Africa/Juba", selected: false },
  { key: "Africa/Khartoum", value: "Africa/Khartoum", selected: false },
  { key: "Africa/Lagos", value: "Africa/Lagos", selected: false },
  { key: "Africa/Maputo", value: "Africa/Maputo", selected: false },
  { key: "Africa/Monrovia", value: "Africa/Monrovia", selected: false },
  { key: "Africa/Nairobi", value: "Africa/Nairobi", selected: false },
  { key: "Africa/Ndjamena", value: "Africa/Ndjamena", selected: false },
  { key: "Africa/Sao_Tome", value: "Africa/Sao_Tome", selected: false },
  { key: "Africa/Tripoli", value: "Africa/Tripoli", selected: false },
  { key: "Africa/Tunis", value: "Africa/Tunis", selected: false },
  { key: "Africa/Windhoek", value: "Africa/Windhoek", selected: false },
  { key: "America/Adak", value: "America/Adak", selected: false },
  { key: "America/Anchorage", value: "America/Anchorage", selected: false },
  { key: "America/Araguaina", value: "America/Araguaina", selected: false },
  {
    key: "America/Argentina/Buenos_Aires",
    value: "America/Argentina/Buenos_Aires",
    selected: false,
  },
  {
    key: "America/Argentina/Catamarca",
    value: "America/Argentina/Catamarca",
    selected: false,
  },
  {
    key: "America/Argentina/Cordoba",
    value: "America/Argentina/Cordoba",
    selected: false,
  },
  {
    key: "America/Argentina/Jujuy",
    value: "America/Argentina/Jujuy",
    selected: false,
  },
  {
    key: "America/Argentina/La_Rioja",
    value: "America/Argentina/La_Rioja",
    selected: false,
  },
  {
    key: "America/Argentina/Mendoza",
    value: "America/Argentina/Mendoza",
    selected: false,
  },
  {
    key: "America/Argentina/Rio_Gallegos",
    value: "America/Argentina/Rio_Gallegos",
    selected: false,
  },
  {
    key: "America/Argentina/Salta",
    value: "America/Argentina/Salta",
    selected: false,
  },
  {
    key: "America/Argentina/San_Juan",
    value: "America/Argentina/San_Juan",
    selected: false,
  },
  {
    key: "America/Argentina/San_Luis",
    value: "America/Argentina/San_Luis",
    selected: false,
  },
  {
    key: "America/Argentina/Tucuman",
    value: "America/Argentina/Tucuman",
    selected: false,
  },
  {
    key: "America/Argentina/Ushuaia",
    value: "America/Argentina/Ushuaia",
    selected: false,
  },
  { key: "America/Asuncion", value: "America/Asuncion", selected: false },
  { key: "America/Atikokan", value: "America/Atikokan", selected: false },
  { key: "America/Bahia", value: "America/Bahia", selected: false },
  {
    key: "America/Bahia_Banderas",
    value: "America/Bahia_Banderas",
    selected: false,
  },
  { key: "America/Barbados", value: "America/Barbados", selected: false },
  { key: "America/Belem", value: "America/Belem", selected: false },
  { key: "America/Belize", value: "America/Belize", selected: false },
  {
    key: "America/Blanc-Sablon",
    value: "America/Blanc-Sablon",
    selected: false,
  },
  { key: "America/Boa_Vista", value: "America/Boa_Vista", selected: false },
  { key: "America/Bogota", value: "America/Bogota", selected: false },
  { key: "America/Boise", value: "America/Boise", selected: false },
  {
    key: "America/Cambridge_Bay",
    value: "America/Cambridge_Bay",
    selected: false,
  },
  {
    key: "America/Campo_Grande",
    value: "America/Campo_Grande",
    selected: false,
  },
  { key: "America/Cancun", value: "America/Cancun", selected: false },
  { key: "America/Caracas", value: "America/Caracas", selected: false },
  { key: "America/Cayenne", value: "America/Cayenne", selected: false },
  { key: "America/Chicago", value: "America/Chicago", selected: false },
  { key: "America/Chihuahua", value: "America/Chihuahua", selected: false },
  { key: "America/Costa_Rica", value: "America/Costa_Rica", selected: false },
  { key: "America/Creston", value: "America/Creston", selected: false },
  { key: "America/Cuiaba", value: "America/Cuiaba", selected: false },
  { key: "America/Curacao", value: "America/Curacao", selected: false },
  {
    key: "America/Danmarkshavn",
    value: "America/Danmarkshavn",
    selected: false,
  },
  { key: "America/Dawson", value: "America/Dawson", selected: false },
  {
    key: "America/Dawson_Creek",
    value: "America/Dawson_Creek",
    selected: false,
  },
  { key: "America/Denver", value: "America/Denver", selected: false },
  { key: "America/Detroit", value: "America/Detroit", selected: false },
  { key: "America/Edmonton", value: "America/Edmonton", selected: false },
  { key: "America/Eirunepe", value: "America/Eirunepe", selected: false },
  { key: "America/El_Salvador", value: "America/El_Salvador", selected: false },
  { key: "America/Fort_Nelson", value: "America/Fort_Nelson", selected: false },
  { key: "America/Fortaleza", value: "America/Fortaleza", selected: false },
  { key: "America/Glace_Bay", value: "America/Glace_Bay", selected: false },
  { key: "America/Godthab", value: "America/Godthab", selected: false },
  { key: "America/Goose_Bay", value: "America/Goose_Bay", selected: false },
  { key: "America/Grand_Turk", value: "America/Grand_Turk", selected: false },
  { key: "America/Guatemala", value: "America/Guatemala", selected: false },
  { key: "America/Guayaquil", value: "America/Guayaquil", selected: false },
  { key: "America/Guyana", value: "America/Guyana", selected: false },
  { key: "America/Halifax", value: "America/Halifax", selected: false },
  { key: "America/Havana", value: "America/Havana", selected: false },
  { key: "America/Hermosillo", value: "America/Hermosillo", selected: false },
  {
    key: "America/Indiana/Indianapolis",
    value: "America/Indiana/Indianapolis",
    selected: false,
  },
  {
    key: "America/Indiana/Knox",
    value: "America/Indiana/Knox",
    selected: false,
  },
  {
    key: "America/Indiana/Marengo",
    value: "America/Indiana/Marengo",
    selected: false,
  },
  {
    key: "America/Indiana/Petersburg",
    value: "America/Indiana/Petersburg",
    selected: false,
  },
  {
    key: "America/Indiana/Tell_City",
    value: "America/Indiana/Tell_City",
    selected: false,
  },
  {
    key: "America/Indiana/Vevay",
    value: "America/Indiana/Vevay",
    selected: false,
  },
  {
    key: "America/Indiana/Vincennes",
    value: "America/Indiana/Vincennes",
    selected: false,
  },
  {
    key: "America/Indiana/Winamac",
    value: "America/Indiana/Winamac",
    selected: false,
  },
  { key: "America/Inuvik", value: "America/Inuvik", selected: false },
  { key: "America/Iqaluit", value: "America/Iqaluit", selected: false },
  { key: "America/Jamaica", value: "America/Jamaica", selected: false },
  { key: "America/Juneau", value: "America/Juneau", selected: false },
  {
    key: "America/Kentucky/Louisville",
    value: "America/Kentucky/Louisville",
    selected: false,
  },
  {
    key: "America/Kentucky/Monticello",
    value: "America/Kentucky/Monticello",
    selected: false,
  },
  { key: "America/La_Paz", value: "America/La_Paz", selected: false },
  { key: "America/Lima", value: "America/Lima", selected: false },
  { key: "America/Los_Angeles", value: "America/Los_Angeles", selected: false },
  { key: "America/Maceio", value: "America/Maceio", selected: false },
  { key: "America/Managua", value: "America/Managua", selected: false },
  { key: "America/Manaus", value: "America/Manaus", selected: false },
  { key: "America/Martinique", value: "America/Martinique", selected: false },
  { key: "America/Matamoros", value: "America/Matamoros", selected: false },
  { key: "America/Mazatlan", value: "America/Mazatlan", selected: false },
  { key: "America/Menominee", value: "America/Menominee", selected: false },
  { key: "America/Merida", value: "America/Merida", selected: false },
  { key: "America/Metlakatla", value: "America/Metlakatla", selected: false },
  { key: "America/Mexico_City", value: "America/Mexico_City", selected: false },
  { key: "America/Miquelon", value: "America/Miquelon", selected: false },
  { key: "America/Moncton", value: "America/Moncton", selected: false },
  { key: "America/Monterrey", value: "America/Monterrey", selected: false },
  { key: "America/Montevideo", value: "America/Montevideo", selected: false },
  { key: "America/Nassau", value: "America/Nassau", selected: false },
  { key: "America/New_York", value: "America/New_York", selected: false },
  { key: "America/Nipigon", value: "America/Nipigon", selected: false },
  { key: "America/Nome", value: "America/Nome", selected: false },
  { key: "America/Noronha", value: "America/Noronha", selected: false },
  {
    key: "America/North_Dakota/Beulah",
    value: "America/North_Dakota/Beulah",
    selected: false,
  },
  {
    key: "America/North_Dakota/Center",
    value: "America/North_Dakota/Center",
    selected: false,
  },
  {
    key: "America/North_Dakota/New_Salem",
    value: "America/North_Dakota/New_Salem",
    selected: false,
  },
  { key: "America/Ojinaga", value: "America/Ojinaga", selected: false },
  { key: "America/Panama", value: "America/Panama", selected: false },
  { key: "America/Pangnirtung", value: "America/Pangnirtung", selected: false },
  { key: "America/Paramaribo", value: "America/Paramaribo", selected: false },
  { key: "America/Phoenix", value: "America/Phoenix", selected: false },
  {
    key: "America/Port-au-Prince",
    value: "America/Port-au-Prince",
    selected: false,
  },
  {
    key: "America/Port_of_Spain",
    value: "America/Port_of_Spain",
    selected: false,
  },
  { key: "America/Porto_Velho", value: "America/Porto_Velho", selected: false },
  { key: "America/Puerto_Rico", value: "America/Puerto_Rico", selected: false },
  {
    key: "America/Punta_Arenas",
    value: "America/Punta_Arenas",
    selected: false,
  },
  { key: "America/Rainy_River", value: "America/Rainy_River", selected: false },
  {
    key: "America/Rankin_Inlet",
    value: "America/Rankin_Inlet",
    selected: false,
  },
  { key: "America/Recife", value: "America/Recife", selected: false },
  { key: "America/Regina", value: "America/Regina", selected: false },
  { key: "America/Resolute", value: "America/Resolute", selected: false },
  { key: "America/Rio_Branco", value: "America/Rio_Branco", selected: false },
  { key: "America/Santarem", value: "America/Santarem", selected: false },
  { key: "America/Santiago", value: "America/Santiago", selected: false },
  {
    key: "America/Santo_Domingo",
    value: "America/Santo_Domingo",
    selected: false,
  },
  { key: "America/Sao_Paulo", value: "America/Sao_Paulo", selected: false },
  {
    key: "America/Scoresbysund",
    value: "America/Scoresbysund",
    selected: false,
  },
  { key: "America/Sitka", value: "America/Sitka", selected: false },
  { key: "America/St_Johns", value: "America/St_Johns", selected: false },
  {
    key: "America/Swift_Current",
    value: "America/Swift_Current",
    selected: false,
  },
  { key: "America/Tegucigalpa", value: "America/Tegucigalpa", selected: false },
  { key: "America/Thule", value: "America/Thule", selected: false },
  { key: "America/Thunder_Bay", value: "America/Thunder_Bay", selected: false },
  { key: "America/Tijuana", value: "America/Tijuana", selected: false },
  { key: "America/Toronto", value: "America/Toronto", selected: false },
  { key: "America/Vancouver", value: "America/Vancouver", selected: false },
  { key: "America/Whitehorse", value: "America/Whitehorse", selected: false },
  { key: "America/Winnipeg", value: "America/Winnipeg", selected: false },
  { key: "America/Yakutat", value: "America/Yakutat", selected: false },
  { key: "America/Yellowknife", value: "America/Yellowknife", selected: false },
  { key: "Antarctica/Casey", value: "Antarctica/Casey", selected: false },
  { key: "Antarctica/Davis", value: "Antarctica/Davis", selected: false },
  {
    key: "Antarctica/DumontDUrville",
    value: "Antarctica/DumontDUrville",
    selected: false,
  },
  {
    key: "Antarctica/Macquarie",
    value: "Antarctica/Macquarie",
    selected: false,
  },
  { key: "Antarctica/Mawson", value: "Antarctica/Mawson", selected: false },
  { key: "Antarctica/Palmer", value: "Antarctica/Palmer", selected: false },
  { key: "Antarctica/Rothera", value: "Antarctica/Rothera", selected: false },
  { key: "Antarctica/Syowa", value: "Antarctica/Syowa", selected: false },
  { key: "Antarctica/Troll", value: "Antarctica/Troll", selected: false },
  { key: "Antarctica/Vostok", value: "Antarctica/Vostok", selected: false },
  { key: "Asia/Almaty", value: "Asia/Almaty", selected: false },
  { key: "Asia/Amman", value: "Asia/Amman", selected: false },
  { key: "Asia/Anadyr", value: "Asia/Anadyr", selected: false },
  { key: "Asia/Aqtau", value: "Asia/Aqtau", selected: false },
  { key: "Asia/Aqtobe", value: "Asia/Aqtobe", selected: false },
  { key: "Asia/Ashgabat", value: "Asia/Ashgabat", selected: false },
  { key: "Asia/Atyrau", value: "Asia/Atyrau", selected: false },
  { key: "Asia/Baghdad", value: "Asia/Baghdad", selected: false },
  { key: "Asia/Baku", value: "Asia/Baku", selected: false },
  { key: "Asia/Bangkok", value: "Asia/Bangkok", selected: false },
  { key: "Asia/Barnaul", value: "Asia/Barnaul", selected: false },
  { key: "Asia/Beirut", value: "Asia/Beirut", selected: false },
  { key: "Asia/Bishkek", value: "Asia/Bishkek", selected: false },
  { key: "Asia/Brunei", value: "Asia/Brunei", selected: false },
  { key: "Asia/Chita", value: "Asia/Chita", selected: false },
  { key: "Asia/Choibalsan", value: "Asia/Choibalsan", selected: false },
  { key: "Asia/Colombo", value: "Asia/Colombo", selected: false },
  { key: "Asia/Damascus", value: "Asia/Damascus", selected: false },
  { key: "Asia/Dhaka", value: "Asia/Dhaka", selected: false },
  { key: "Asia/Dili", value: "Asia/Dili", selected: false },
  { key: "Asia/Dubai", value: "Asia/Dubai", selected: false },
  { key: "Asia/Dushanbe", value: "Asia/Dushanbe", selected: false },
  { key: "Asia/Famagusta", value: "Asia/Famagusta", selected: false },
  { key: "Asia/Gaza", value: "Asia/Gaza", selected: false },
  { key: "Asia/Hebron", value: "Asia/Hebron", selected: false },
  { key: "Asia/Ho_Chi_Minh", value: "Asia/Ho_Chi_Minh", selected: false },
  { key: "Asia/Hong_Kong", value: "Asia/Hong_Kong", selected: false },
  { key: "Asia/Hovd", value: "Asia/Hovd", selected: false },
  { key: "Asia/Irkutsk", value: "Asia/Irkutsk", selected: false },
  { key: "Asia/Jakarta", value: "Asia/Jakarta", selected: false },
  { key: "Asia/Jayapura", value: "Asia/Jayapura", selected: false },
  { key: "Asia/Jerusalem", value: "Asia/Jerusalem", selected: false },
  { key: "Asia/Kabul", value: "Asia/Kabul", selected: false },
  { key: "Asia/Kamchatka", value: "Asia/Kamchatka", selected: false },
  { key: "Asia/Karachi", value: "Asia/Karachi", selected: false },
  { key: "Asia/Kathmandu", value: "Asia/Kathmandu", selected: false },
  { key: "Asia/Khandyga", value: "Asia/Khandyga", selected: false },
  { key: "Asia/Kolkata", value: "Asia/Kolkata", selected: false },
  { key: "Asia/Krasnoyarsk", value: "Asia/Krasnoyarsk", selected: false },
  { key: "Asia/Kuala_Lumpur", value: "Asia/Kuala_Lumpur", selected: false },
  { key: "Asia/Kuching", value: "Asia/Kuching", selected: false },
  { key: "Asia/Macau", value: "Asia/Macau", selected: false },
  { key: "Asia/Magadan", value: "Asia/Magadan", selected: false },
  { key: "Asia/Makassar", value: "Asia/Makassar", selected: false },
  { key: "Asia/Manila", value: "Asia/Manila", selected: false },
  { key: "Asia/Nicosia", value: "Asia/Nicosia", selected: false },
  { key: "Asia/Novokuznetsk", value: "Asia/Novokuznetsk", selected: false },
  { key: "Asia/Novosibirsk", value: "Asia/Novosibirsk", selected: false },
  { key: "Asia/Omsk", value: "Asia/Omsk", selected: false },
  { key: "Asia/Oral", value: "Asia/Oral", selected: false },
  { key: "Asia/Pontianak", value: "Asia/Pontianak", selected: false },
  { key: "Asia/Pyongyang", value: "Asia/Pyongyang", selected: false },
  { key: "Asia/Qatar", value: "Asia/Qatar", selected: false },
  { key: "Asia/Qostanay", value: "Asia/Qostanay", selected: false },
  { key: "Asia/Qyzylorda", value: "Asia/Qyzylorda", selected: false },
  { key: "Asia/Riyadh", value: "Asia/Riyadh", selected: false },
  { key: "Asia/Sakhalin", value: "Asia/Sakhalin", selected: false },
  { key: "Asia/Samarkand", value: "Asia/Samarkand", selected: false },
  { key: "Asia/Seoul", value: "Asia/Seoul", selected: false },
  { key: "Asia/Shanghai", value: "Asia/Shanghai", selected: false },
  { key: "Asia/Singapore", value: "Asia/Singapore", selected: false },
  { key: "Asia/Srednekolymsk", value: "Asia/Srednekolymsk", selected: false },
  { key: "Asia/Taipei", value: "Asia/Taipei", selected: false },
  { key: "Asia/Tashkent", value: "Asia/Tashkent", selected: false },
  { key: "Asia/Tbilisi", value: "Asia/Tbilisi", selected: false },
  { key: "Asia/Tehran", value: "Asia/Tehran", selected: false },
  { key: "Asia/Thimphu", value: "Asia/Thimphu", selected: false },
  { key: "Asia/Tokyo", value: "Asia/Tokyo", selected: false },
  { key: "Asia/Tomsk", value: "Asia/Tomsk", selected: false },
  { key: "Asia/Ulaanbaatar", value: "Asia/Ulaanbaatar", selected: false },
  { key: "Asia/Urumqi", value: "Asia/Urumqi", selected: false },
  { key: "Asia/Ust-Nera", value: "Asia/Ust-Nera", selected: false },
  { key: "Asia/Vladivostok", value: "Asia/Vladivostok", selected: false },
  { key: "Asia/Yakutsk", value: "Asia/Yakutsk", selected: false },
  { key: "Asia/Yangon", value: "Asia/Yangon", selected: false },
  { key: "Asia/Yekaterinburg", value: "Asia/Yekaterinburg", selected: false },
  { key: "Asia/Yerevan", value: "Asia/Yerevan", selected: false },
  { key: "Atlantic/Azores", value: "Atlantic/Azores", selected: false },
  { key: "Atlantic/Bermuda", value: "Atlantic/Bermuda", selected: false },
  { key: "Atlantic/Canary", value: "Atlantic/Canary", selected: false },
  { key: "Atlantic/Cape_Verde", value: "Atlantic/Cape_Verde", selected: false },
  { key: "Atlantic/Faroe", value: "Atlantic/Faroe", selected: false },
  { key: "Atlantic/Madeira", value: "Atlantic/Madeira", selected: false },
  { key: "Atlantic/Reykjavik", value: "Atlantic/Reykjavik", selected: false },
  {
    key: "Atlantic/South_Georgia",
    value: "Atlantic/South_Georgia",
    selected: false,
  },
  { key: "Atlantic/Stanley", value: "Atlantic/Stanley", selected: false },
  { key: "Australia/Adelaide", value: "Australia/Adelaide", selected: false },
  { key: "Australia/Brisbane", value: "Australia/Brisbane", selected: false },
  {
    key: "Australia/Broken_Hill",
    value: "Australia/Broken_Hill",
    selected: false,
  },
  { key: "Australia/Currie", value: "Australia/Currie", selected: false },
  { key: "Australia/Darwin", value: "Australia/Darwin", selected: false },
  { key: "Australia/Eucla", value: "Australia/Eucla", selected: false },
  { key: "Australia/Hobart", value: "Australia/Hobart", selected: false },
  { key: "Australia/Lindeman", value: "Australia/Lindeman", selected: false },
  { key: "Australia/Lord_Howe", value: "Australia/Lord_Howe", selected: false },
  { key: "Australia/Melbourne", value: "Australia/Melbourne", selected: false },
  { key: "Australia/Perth", value: "Australia/Perth", selected: false },
  { key: "Australia/Sydney", value: "Australia/Sydney", selected: false },
  { key: "Europe/Amsterdam", value: "Europe/Amsterdam", selected: false },
  { key: "Europe/Andorra", value: "Europe/Andorra", selected: false },
  { key: "Europe/Astrakhan", value: "Europe/Astrakhan", selected: false },
  { key: "Europe/Athens", value: "Europe/Athens", selected: false },
  { key: "Europe/Belgrade", value: "Europe/Belgrade", selected: false },
  { key: "Europe/Berlin", value: "Europe/Berlin", selected: false },
  { key: "Europe/Brussels", value: "Europe/Brussels", selected: false },
  { key: "Europe/Bucharest", value: "Europe/Bucharest", selected: false },
  { key: "Europe/Budapest", value: "Europe/Budapest", selected: false },
  { key: "Europe/Chisinau", value: "Europe/Chisinau", selected: false },
  { key: "Europe/Copenhagen", value: "Europe/Copenhagen", selected: false },
  { key: "Europe/Dublin", value: "Europe/Dublin", selected: false },
  { key: "Europe/Gibraltar", value: "Europe/Gibraltar", selected: false },
  { key: "Europe/Helsinki", value: "Europe/Helsinki", selected: false },
  { key: "Europe/Istanbul", value: "Europe/Istanbul", selected: false },
  { key: "Europe/Kaliningrad", value: "Europe/Kaliningrad", selected: false },
  { key: "Europe/Kiev", value: "Europe/Kiev", selected: false },
  { key: "Europe/Kirov", value: "Europe/Kirov", selected: false },
  { key: "Europe/Lisbon", value: "Europe/Lisbon", selected: false },
  { key: "Europe/London", value: "Europe/London", selected: false },
  { key: "Europe/Luxembourg", value: "Europe/Luxembourg", selected: false },
  { key: "Europe/Madrid", value: "Europe/Madrid", selected: false },
  { key: "Europe/Malta", value: "Europe/Malta", selected: false },
  { key: "Europe/Minsk", value: "Europe/Minsk", selected: false },
  { key: "Europe/Monaco", value: "Europe/Monaco", selected: false },
  { key: "Europe/Moscow", value: "Europe/Moscow", selected: false },
  { key: "Europe/Oslo", value: "Europe/Oslo", selected: false },
  { key: "Europe/Paris", value: "Europe/Paris", selected: false },
  { key: "Europe/Prague", value: "Europe/Prague", selected: false },
  { key: "Europe/Riga", value: "Europe/Riga", selected: false },
  { key: "Europe/Rome", value: "Europe/Rome", selected: false },
  { key: "Europe/Samara", value: "Europe/Samara", selected: false },
  { key: "Europe/Saratov", value: "Europe/Saratov", selected: false },
  { key: "Europe/Simferopol", value: "Europe/Simferopol", selected: false },
  { key: "Europe/Sofia", value: "Europe/Sofia", selected: false },
  { key: "Europe/Stockholm", value: "Europe/Stockholm", selected: false },
  { key: "Europe/Tallinn", value: "Europe/Tallinn", selected: false },
  { key: "Europe/Tirane", value: "Europe/Tirane", selected: false },
  { key: "Europe/Ulyanovsk", value: "Europe/Ulyanovsk", selected: false },
  { key: "Europe/Uzhgorod", value: "Europe/Uzhgorod", selected: false },
  { key: "Europe/Vienna", value: "Europe/Vienna", selected: false },
  { key: "Europe/Vilnius", value: "Europe/Vilnius", selected: false },
  { key: "Europe/Volgograd", value: "Europe/Volgograd", selected: false },
  { key: "Europe/Warsaw", value: "Europe/Warsaw", selected: false },
  { key: "Europe/Zaporozhye", value: "Europe/Zaporozhye", selected: false },
  { key: "Europe/Zurich", value: "Europe/Zurich", selected: false },
  { key: "Indian/Chagos", value: "Indian/Chagos", selected: false },
  { key: "Indian/Christmas", value: "Indian/Christmas", selected: false },
  { key: "Indian/Cocos", value: "Indian/Cocos", selected: false },
  { key: "Indian/Kerguelen", value: "Indian/Kerguelen", selected: false },
  { key: "Indian/Mahe", value: "Indian/Mahe", selected: false },
  { key: "Indian/Maldives", value: "Indian/Maldives", selected: false },
  { key: "Indian/Mauritius", value: "Indian/Mauritius", selected: false },
  { key: "Indian/Reunion", value: "Indian/Reunion", selected: false },
  { key: "Pacific/Apia", value: "Pacific/Apia", selected: false },
  { key: "Pacific/Auckland", value: "Pacific/Auckland", selected: false },
  {
    key: "Pacific/Bougainville",
    value: "Pacific/Bougainville",
    selected: false,
  },
  { key: "Pacific/Chatham", value: "Pacific/Chatham", selected: false },
  { key: "Pacific/Chuuk", value: "Pacific/Chuuk", selected: false },
  { key: "Pacific/Easter", value: "Pacific/Easter", selected: false },
  { key: "Pacific/Efate", value: "Pacific/Efate", selected: false },
  { key: "Pacific/Enderbury", value: "Pacific/Enderbury", selected: false },
  { key: "Pacific/Fakaofo", value: "Pacific/Fakaofo", selected: false },
  { key: "Pacific/Fiji", value: "Pacific/Fiji", selected: false },
  { key: "Pacific/Funafuti", value: "Pacific/Funafuti", selected: false },
  { key: "Pacific/Galapagos", value: "Pacific/Galapagos", selected: false },
  { key: "Pacific/Gambier", value: "Pacific/Gambier", selected: false },
  { key: "Pacific/Guadalcanal", value: "Pacific/Guadalcanal", selected: false },
  { key: "Pacific/Guam", value: "Pacific/Guam", selected: false },
  { key: "Pacific/Honolulu", value: "Pacific/Honolulu", selected: false },
  { key: "Pacific/Kiritimati", value: "Pacific/Kiritimati", selected: false },
  { key: "Pacific/Kosrae", value: "Pacific/Kosrae", selected: false },
  { key: "Pacific/Kwajalein", value: "Pacific/Kwajalein", selected: false },
  { key: "Pacific/Majuro", value: "Pacific/Majuro", selected: false },
  { key: "Pacific/Marquesas", value: "Pacific/Marquesas", selected: false },
  { key: "Pacific/Nauru", value: "Pacific/Nauru", selected: false },
  { key: "Pacific/Niue", value: "Pacific/Niue", selected: false },
  { key: "Pacific/Norfolk", value: "Pacific/Norfolk", selected: false },
  { key: "Pacific/Noumea", value: "Pacific/Noumea", selected: false },
  { key: "Pacific/Pago_Pago", value: "Pacific/Pago_Pago", selected: false },
  { key: "Pacific/Palau", value: "Pacific/Palau", selected: false },
  { key: "Pacific/Pitcairn", value: "Pacific/Pitcairn", selected: false },
  { key: "Pacific/Pohnpei", value: "Pacific/Pohnpei", selected: false },
  {
    key: "Pacific/Port_Moresby",
    value: "Pacific/Port_Moresby",
    selected: false,
  },
  { key: "Pacific/Rarotonga", value: "Pacific/Rarotonga", selected: false },
  { key: "Pacific/Tahiti", value: "Pacific/Tahiti", selected: false },
  { key: "Pacific/Tarawa", value: "Pacific/Tarawa", selected: false },
  { key: "Pacific/Tongatapu", value: "Pacific/Tongatapu", selected: false },
  { key: "Pacific/Wake", value: "Pacific/Wake", selected: false },
  { key: "Pacific/Wallis", value: "Pacific/Wallis", selected: false },
];

export const MONTH_FULL = {
  0: "January",
  1: "February",
  2: "March",
  3: "April",
  4: "May",
  5: "June",
  6: "July",
  7: "August",
  8: "September",
  9: "October",
  10: "November",
  11: "December",
} as const;

export const DAY_OF_WEEK = {
  0: "Sun",
  1: "Mon",
  2: "Tue",
  3: "Wed",
  4: "Thu",
  5: "Fri",
  6: "Sat",
} as const;

export const DAY_OF_WEEK_FULL = {
  0: "Sunday",
  1: "Monday",
  2: "Tuesday",
  3: "Wednesday",
  4: "Thursday",
  5: "Friday",
  6: "Saturday",
} as const;

export const DAY_INDEX_MAP = {
  0: "sunday",
  1: "monday",
  2: "tuesday",
  3: "wednesday",
  4: "thursday",
  5: "friday",
  6: "saturday",
  sunday: 0,
  monday: 1,
  tuesday: 2,
  wednesday: 3,
  thursday: 4,
  friday: 5,
  saturday: 6,
} as const;

export const ONE_MINUTE_IN_MS = 60 * 1000;
export const ONE_HOUR_IN_MS = ONE_MINUTE_IN_MS * 60;
export const ONE_DAY_IN_MS = ONE_HOUR_IN_MS * 24;
export const ONE_MONTH_IN_MS = ONE_DAY_IN_MS * 30;
export const ONE_YEAR_IN_MS = ONE_DAY_IN_MS * 365;
